-- ==========================================================
-- Mio Wealth (Investman) Database Schema
-- Standard ANSI SQL DDL compatible across PostgreSQL & MySQL
-- ==========================================================

-- 1. User Credentials
CREATE TABLE IF NOT EXISTS user_login (
    user_id VARCHAR(100) NOT NULL PRIMARY KEY,
    password VARCHAR(255) NOT NULL
);

-- 2. User Profile
CREATE TABLE IF NOT EXISTS user_profile (
    user_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    last_name VARCHAR(100) NOT NULL,
    email_id VARCHAR(150) NOT NULL,
    mobile_number VARCHAR(30),
    profile_picture VARCHAR(255),
    user_id VARCHAR(100) UNIQUE,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_profile_user FOREIGN KEY (user_id) REFERENCES user_login (user_id) ON DELETE CASCADE
);

-- 3. User Addresses
CREATE TABLE IF NOT EXISTS user_address (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line1 VARCHAR(255),
    line2 VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100),
    postal_code VARCHAR(20),
    user_profile_id BIGINT,
    CONSTRAINT fk_user_address_profile FOREIGN KEY (user_profile_id) REFERENCES user_profile (user_profile_id) ON DELETE CASCADE
);

-- 4. Investments
CREATE TABLE IF NOT EXISTS investment (
    investment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DOUBLE PRECISION DEFAULT 0.0,
    quantity INT DEFAULT 0,
    investment_date TIMESTAMP,
    remarks VARCHAR(255),
    action VARCHAR(50),
    user_id VARCHAR(100),
    CONSTRAINT fk_investment_user FOREIGN KEY (user_id) REFERENCES user_login (user_id) ON DELETE CASCADE
);

-- 5. Investment Types
CREATE TABLE IF NOT EXISTS investment_type (
    type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50),
    type_name VARCHAR(100),
    description VARCHAR(255),
    investment_id BIGINT,
    CONSTRAINT fk_type_investment FOREIGN KEY (investment_id) REFERENCES investment (investment_id) ON DELETE CASCADE
);

-- 6. Savings
CREATE TABLE IF NOT EXISTS saving (
    saving_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DOUBLE PRECISION DEFAULT 0.0,
    saving_date TIMESTAMP,
    remarks VARCHAR(255),
    action VARCHAR(50),
    user_id VARCHAR(100),
    CONSTRAINT fk_saving_user FOREIGN KEY (user_id) REFERENCES user_login (user_id) ON DELETE CASCADE
);
